### ISSUE TITLE
Normal data download broken

### ISSUE THREAD

**Issue by smacisaac** [NickHeiner/decomissioned-fitbit-export#16]
Past few days on your app. Hit the normal login and this came up:

> `Oops! Something broke.
Here's the error:

{
  "message": "Response code 401 (Unauthorized)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/steps/date/today/max.json",
  "statusCode": 401,
  "statusMessage": "Unauthorized",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/steps/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"expired_token\",\"message\":\"Access token expired: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzTkxOTkoiLCJhdWQiOiIyMjlDSkgiLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZXMiOiJyd2VpIHJhY3Qgcm51dCBycHJvIHJzbGUiLCJleHAiOjE0ODgxNzAzOTQsImlhdCI6MTQ4ODE0MTU5NH0.2DQZ2mMwaAQ8477-12fiV6Il58Vzu7v_B6btG2jvc3g. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process.\"}],\"success\":false}"
}
HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.e (\\100.82.74.7\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedPromise.linkTransaction (\\100.82.74.7\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:168:23)
    at wrappedPromise.wrapped [as __NR_wrapper] (\\100.82.74.7\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at wrappedHandler (\\100.82.74.7\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:202:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
`

**Comment by jenllip** [comment]
I also received this error just now. I was still "logged in" from having done a download a few days ago, but trying again in an incognito window (requiring a fresh login to Fitbit) seemed to work. I do not see a way to "log out" in order to reset my non-incognito session; perhaps that would mitigate the problem?


{
  "message": "Response code 401 (Unauthorized)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/caloriesBMR/date/today/max.json",
  "statusCode": 401,
  "statusMessage": "Unauthorized",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/caloriesBMR/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"expired_token\",\"message\":\"Access token expired: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMjg4Q1kiLCJhdWQiOiIyMjlDSkgiLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZXMiOiJyd2VpIHJhY3Qgcm51dCBycHJvIHJzbGUiLCJleHAiOjE0ODg0MTUwMjYsImlhdCI6MTQ4ODM4NjIyNn0.-nsG8GmrG8LWcx9LxXNG_8f__yjH2fKq1VSD3stXfPE. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process.\"}],\"success\":false}"
}
HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.e (\\100.82.74.7\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedPromise.linkTransaction (\\100.82.74.7\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:168:23)
    at wrappedPromise.wrapped [as __NR_wrapper] (\\100.82.74.7\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at wrappedHandler (\\100.82.74.7\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:202:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by NickHeiner** [comment]
Hmm. I was able to log in just now and it worked for me.

@jenllip I don't have a way to log out now. In lieu of that, you can manually clear your cookies for http://fitbit-export.azurewebsites.net/ and for Fitbit. That will force you to re-log in.

Are you both seeing this after you click the "log in" button, or after you click the "download all available data" button?

**Comment by jenllip** [comment]
This was after clicking "download all available data."

**Comment by RipsterBolton** [comment]
I got this error... What do I do?

Fitbit broke.
Here's the error:

{
  "message": "Response code 500 (Internal Server Error)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/minutesVeryActive/date/today/max.json",
  "statusCode": 500,
  "statusMessage": "Internal Server Error",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/minutesVeryActive/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"request\",\"fieldName\":\"500\",\"message\":\"An error occurred with the Fitbit Web API while processing the request. Error id: AC451626:4F81_A92D91CB:01BB_5B0F178C_9D3D4BAA:4F76\"}],\"success\":false}"
}
HTTPError: Response code 500 (Internal Server Error)
    at stream.catch.then.e (D:\home\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedHandler (D:\home\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:201:48)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Fitbit's servers crashed when trying to produce your data. You can report this to me on GitHub., but to be honest there's not much I'll be able to do about Fitbit being broken. You can also report this to Fitbit directly on their Developer Board. Good luck!

**Comment by NickHeiner** [comment]
Fitbit now has a [complete export](https://www.fitbit.com/settings/data/export) on their site. I have decommissioned this project, since it's now 
(thankfully) obsolete. Thanks for everyone's interest!
