### ISSUE TITLE
Won't downaload data

### ISSUE THREAD

**Issue by maisiec** [NickHeiner/decomissioned-fitbit-export#17]
when trying to download all fitbit data this is the error I get. 

Here's the error:

{
  "message": "Response code 403 (Forbidden)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/foods/log/caloriesIn/date/today/max.json",
  "statusCode": 403,
  "statusMessage": "Forbidden",
  "requestUrl": "https://api.fitbit.com/1/user/-/foods/log/caloriesIn/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"insufficient_scope\",\"message\":\"This application does not have permission to access nutrition data. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process.\"}],\"success\":false}"
}
HTTPError: Response code 403 (Forbidden)
    at stream.catch.then.e (\\100.82.66.112\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedPromise.linkTransaction (\\100.82.66.112\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:168:23)
    at wrappedPromise.wrapped [as __NR_wrapper] (\\100.82.66.112\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at wrappedHandler (\\100.82.66.112\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:202:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by NickHeiner** [comment]
Fitbit now has a [complete export](https://www.fitbit.com/settings/data/export) on their site. I have decommissioned this project, since it's now 
(thankfully) obsolete. Thanks for everyone's interest!
