### ISSUE TITLE
Re Fitbit Export broken

### ISSUE THREAD

**Issue by MartinBlackshaw** [NickHeiner/decomissioned-fitbit-export#18]
Oops! Something broke.
Here's the error:

{
  "message": "Response code 401 (Unauthorized)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/caloriesBMR/date/today/max.json",
  "statusCode": 401,
  "statusMessage": "Unauthorized",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/caloriesBMR/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"expired_token\",\"message\":\"Access token expired: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0TThaRzIiLCJhdWQiOiIyMjlDSkgiLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZXMiOiJyd2VpIHJhY3Qgcm51dCBycHJvIHJzbGUiLCJleHAiOjE1MDQzMjk3ODIsImlhdCI6MTUwNDMwMDk4Mn0.vWGGB0KwGCaZh7dNNut7ZBLnYvwUfcxVr4aFV7Fet1I. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process.\"}],\"success\":false}"
}
HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.e (\\100.82.76.16\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedPromise.linkTransaction (\\100.82.76.16\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:168:23)
    at wrappedPromise.wrapped [as __NR_wrapper] (\\100.82.76.16\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at wrappedHandler (\\100.82.76.16\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:202:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)

I then tried again with the same URL audit worked fine!?!?! So maybe nothing is wrong with the code. All the best,

Martin

**Comment by Sophiafcwang** [comment]
Can't download fibit data, the error message is as below. Please fix it. Thanks.

Oops! Something broke.
Here's the error:

{
  "message": "Response code 401 (Unauthorized)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/caloriesBMR/date/today/max.json",
  "statusCode": 401,
  "statusMessage": "Unauthorized",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/caloriesBMR/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"expired_token\",\"message\":\"Access token expired: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ODVUOTciLCJhdWQiOiIyMjlDSkgiLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZXMiOiJyYWN0IHJwcm8gcnNsZSIsImV4cCI6MTUwNDQ3OTg0OSwiaWF0IjoxNTA0NDUxMDQ5fQ.qoAAB5rsjJZMiesaKeDnH6U3gUoORcgkoIBq6CpVpa8. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process.\"}],\"success\":false}"
}
HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.e (\\100.82.76.16\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedPromise.linkTransaction (\\100.82.76.16\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:168:23)
    at wrappedPromise.wrapped [as __NR_wrapper] (\\100.82.76.16\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at wrappedHandler (\\100.82.76.16\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:202:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by NickHeiner** [comment]
Interesting. Thanks for pasting that error message. It gives me enough to get started. 

I won't have time for a few weeks to take a look at this, as this is a hobby project for me. If you would like to send a pull request updating the code to fix the issue, you're welcome to do so! I'll review and deploy it. Otherwise, I'll post on this issue when I have a fix.

**Comment by MartinBlackshaw** [comment]
Nick,
The problem is fixed by logging into your Fitbit account. Your program worked fine  after logging into fitbit.

All is working fine.

Thanks again,
Martin Blackshaw



On Sep 12, 2017, at 5:52 AM, Nick Heiner <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting. Thanks for pasting that error message. It gives me enough to get started.

I won't have time for a few weeks to take a look at this, as this is a hobby project for me. If you would like to send a pull request updating the code to fix the issue, you're welcome to do so! I'll review and deploy it. Otherwise, I'll post on this issue when I have a fix.

**Comment by NickHeiner** [comment]
Fitbit now has a [complete export](https://www.fitbit.com/settings/data/export) on their site. I have decommissioned this project, since it's now 
(thankfully) obsolete. Thanks for everyone's interest!
