### ISSUE TITLE
Response Code 500

### ISSUE THREAD

**Issue by jeapostrophe** [NickHeiner/decomissioned-fitbit-export#19]
Fitbit broke.
Here's the error:

```
{
  "message": "Response code 500 (Internal Server Error)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/minutesSedentary/date/today/max.json",
  "statusCode": 500,
  "statusMessage": "Internal Server Error",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/minutesSedentary/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"request\",\"fieldName\":\"500\",\"message\":\"An error occurred with the Fitbit Web API while processing the request. Error id: AC4516A4:704B_A92D91CB:01BB_5A391941_6881765C:1D7A\"}],\"success\":false}"
}
```
```
HTTPError: Response code 500 (Internal Server Error)
    at stream.catch.then.e (\\100.82.76.16\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedPromise.linkTransaction (\\100.82.76.16\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:168:23)
    at wrappedPromise.wrapped [as __NR_wrapper] (\\100.82.76.16\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at wrappedHandler (\\100.82.76.16\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:202:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Fitbit's servers crashed when trying to produce your data. You can report this to me on GitHub., but to be honest there's not much I'll be able to do about Fitbit being broken. You can also report this to Fitbit directly on their Developer Board. Good luck!

**Comment by twpol** [comment]
I am seeing the same error; worth noting that the exact Fitbit API that errors out seems to vary, although I've only seen the "activities/minutes" ones so far.

**Comment by klinkehoffen** [comment]
I too have been getting the same error for the past ten days or so:
{
  "message": "Response code 500 (Internal Server Error)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/minutesLightlyActive/date/today/max.json",
  "statusCode": 500,
  "statusMessage": "Internal Server Error",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/minutesLightlyActive/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"request\",\"fieldName\":\"500\",\"message\":\"An error occurred with the Fitbit Web API while processing the request. Error id: AC4516A4:77A9_A92D900A:01BB_5A41859A_92A70D9:175D\"}],\"success\":false}"
}

With another field underneath saying:
HTTPError: Response code 500 (Internal Server Error)
    at stream.catch.then.e (\\100.82.86.34\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedPromise.linkTransaction (\\100.82.86.34\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:168:23)
    at wrappedPromise.wrapped [as __NR_wrapper] (\\100.82.86.34\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at wrappedHandler (\\100.82.86.34\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:202:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by klinkehoffen** [comment]
By the way: thank you so much for making this function available. Your solution for extracting fitbit data is so much easier than using Fitbit's own process. Wishing you a very Merry Christmas, and a Happy New Year!

**Comment by steniej** [comment]
I'm getting the same 500 error
{
  "message": "Response code 500 (Internal Server Error)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/minutesFairlyActive/date/today/max.json",
  "statusCode": 500,
  "statusMessage": "Internal Server Error",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/minutesFairlyActive/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"request\",\"fieldName\":\"500\",\"message\":\"An error occurred with the Fitbit Web API while processing the request. Error id: AC4516A4:6AD5_A92D826B:01BB_5A450EC7_3B42E69B:43C4\"}],\"success\":false}"
}

**Comment by andrewjbennett** [comment]
```
{
  "message": "Response code 500 (Internal Server Error)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/minutesLightlyActive/date/today/max.json",
  "statusCode": 500,
  "statusMessage": "Internal Server Error",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/minutesLightlyActive/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"request\",\"fieldName\":\"500\",\"message\":\"An error occurred with the Fitbit Web API while processing the request. Error id: AC4516A4:59B9_A92D91CB:01BB_5A50A756_44500FD6:30CB\"}],\"success\":false}"
}
```

```
HTTPError: Response code 500 (Internal Server Error)
    at stream.catch.then.e (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedPromise.linkTransaction (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:168:23)
    at wrappedPromise.wrapped [as __NR_wrapper] (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at wrappedHandler (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:202:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

If I reload, I get the same error in a different path; so far "minutesVeryActive", "minutesFairlyActive", "minutesSedentary".

**Comment by NickHeiner** [comment]
Hey everyone. Sorry that these errors keep occurring. 

As the error notes, this is a problem on Fitbit's side and there's not really anything I can do about it. :smile:. You can post your errors on the [Fitbit Developer Forum](https://community.fitbit.com/t5/Web-API-Development/bd-p/dev). The `Error id` listed in your error messages should give the Fitbit developers what they need to track down the incident. (For instance, @andrewjbennett's error id is `AC4516A4:59B9_A92D91CB:01BB_5A50A756_44500FD6:30CB`.)

It does seem like these errors are occurring more frequently now than they used to. 😦

**Comment by Amyunimus** [comment]
I'm getting the same error. On the developer forum, they say that this is due to  `max` is not a supported value for time period. Is this something that can be fixed when making the request, or is this still on Fitbit's side?

https://community.fitbit.com/t5/Web-API-Development/api-giving-Response-code-500-Internal-Server-Error-Error-id-A29EFF64-61D9/td-p/2525905

**Comment by danmana** [comment]
Like @Amyunimus says, `max` is not a valid period for the activities API - see [docs](https://dev.fitbit.com/build/reference/web-api/activity/#get-activity-time-series). 
Valid options are `1d, 7d, 30d, 1w, 1m, 3m, 6m, 1y`

You should change in [get-time-series.js](https://github.com/NickHeiner/fitbit-export/blob/9d2398b72abc11d96d54b867b7f46a6a288395b7/app/get-time-series.js#L50) the `timePeriod: 'max'` to `timePeriod: '1y'` (or maybe `99y` if it works)

**Comment by Amyunimus** [comment]
Now getting a similar error except for caloriesIn. Same `max` error will probably keep popping up for all the variables. 


```
{
  "message": "Response code 401 (Unauthorized)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/foods/log/caloriesIn/date/today/max.json",
  "statusCode": 401,
  "statusMessage": "Unauthorized",
  "requestUrl": "https://api.fitbit.com/1/user/-/foods/log/caloriesIn/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"expired_token\",\"message\":\"Access token expired: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzS1hQNDciLCJhdWQiOiIyMjlDSkgiLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZXMiOiJyd2VpIHJhY3Qgcm51dCBycHJvIHJzbGUiLCJleHAiOjE1MjQ0Mzg0MDIsImlhdCI6MTUyNDQwOTYwMn0.matvGwZEiQeIp_3HquzujHUbD2xpBDnET5K__9wGvL8. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process.\"}],\"success\":false}"
}
HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.e (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedPromise.linkTransaction (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:168:23)
    at wrappedPromise.wrapped [as __NR_wrapper] (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at wrappedHandler (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:202:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by NickHeiner** [comment]
Fitbit now has a [complete export](https://www.fitbit.com/settings/data/export) on their site. I have decommissioned this project, since it's now 
(thankfully) obsolete. Thanks for everyone's interest!
