### ISSUE TITLE
Oops! Something broke.

### ISSUE THREAD

**Issue by LionRelaxe** [NickHeiner/decomissioned-fitbit-export#22]
Hello,

I'm just trying to use the exporter at http://fitbit-export.azurewebsites.net .
I am logged at Fitbit, I have app permission in my fitbit account:
"Fitbit Data Export by Nick Heiner Approved on 2018/04/10 10:53:46"

When I go and try to export all, I am given this message, and hence I comply and file an issue ;)

```
Oops! Something broke.
Here's the error:

{
  "message": "Response code 401 (Unauthorized)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/sleep/minutesToFallAsleep/date/today/max.json",
  "statusCode": 401,
  "statusMessage": "Unauthorized",
  "requestUrl": "https://api.fitbit.com/1/user/-/sleep/minutesToFallAsleep/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"expired_token\",\"message\":\"Access token expired: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzM0xONTciLCJhdWQiOiIyMjlDSkgiLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZXMiOiJyd2VpIHJhY3Qgcm51dCBycHJvIHJzbGUiLCJleHAiOjE1MjM0MDA4MjYsImlhdCI6MTUyMzM3MjAyNn0.ORGm57mk4YWXCnii96lh9k2nDCodC8b9JYrf-E0n-Js. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process.\"}],\"success\":false}"
}
HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.e (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedPromise.linkTransaction (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:168:23)
    at wrappedPromise.wrapped [as __NR_wrapper] (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at wrappedHandler (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:202:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
To report this, file an issue on GitHub. Please paste this full error, and provide a detailed description of what you were doing. Thanks!
```

Also, I have tried on various dates and the same problem occured.
I revoked the app permission, then re-done it trough Microsoft Edge. An other error happened:

```
Fitbit broke. 
Here's the error:
{
  "message": "Response code 500 (Internal Server Error)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/minutesLightlyActive/date/today/max.json",
  "statusCode": 500,
  "statusMessage": "Internal Server Error",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/minutesLightlyActive/date/today/max.json",
  "responseBody": "{\"errors\":[{\"errorType\":\"request\",\"fieldName\":\"500\",\"message\":\"An error occurred with the Fitbit Web API while processing the request. Error id: AC451626:812B_A92D826B:01BB_5AE09FF5_10C55068:40E3\"}],\"success\":false}"
}
HTTPError: Response code 500 (Internal Server Error)
    at stream.catch.then.e (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedPromise.linkTransaction (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:168:23)
    at wrappedPromise.wrapped [as __NR_wrapper] (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at wrappedHandler (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:202:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Fitbit's servers crashed when trying to produce your data. You can report this to me on GitHub., but to be honest there's not much I'll be able to do about Fitbit being broken. You can also report this to Fitbit directly on their Developer Board. Good luck! 
```

**Comment by NickHeiner** [comment]
Fitbit now has a [complete export](https://www.fitbit.com/settings/data/export) on their site. I have decommissioned this project, since it's now 
(thankfully) obsolete. Thanks for everyone's interest!
